#!/bin/bash

python3 /home/zoe/'GhassanGT Dropbox'/'Zoe Fowler'/Zoe/InSync/PhDResearch/Code/FedSeismic/main.py --seed=1 --n_rounds=200 --partition_method="dirichlet" --partition_alpha=0.1 --dataset_name='cifar10' --model_name='fedavg_cifar' --root='/media/zoe/ssd/' --n_clients=100 --sample_ratio=0.1 --batch_size=50 --date='example-date' --config_path="/config/fedavg.json"
